[build]
functions = "netlify/functions/"

# Since this app is a SPA (Simgle Page Application)
# Serve all routes the `/index.html`
# All routes need to go through `/index.html`
# or they would return a `404 Not Found` error
# https://www.netlify.com/blog/2020/04/07/creating-better-more-predictable-redirect-rules-for-spas/
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
